version: '2'
services:
  postclipfront:
    container_name: postclipfront
    build: .
    command: "npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/PostClipsFE
      - /PostClipsFE/node_modules
